saved = [
    "do-610588",
    "hu-572329",
    "do-718133",
    "do-21267",
    "do-93589",
    "tw-Bawkbasoup",
    "tw-missmikkaa",
    "tw-PalmBee",
    "tw-csharpfritz",
    "bi-545068",
    "tw-distortion2",
    "tw-the_happy_hob",
    "tw-elajjaz",
    "tw-christitustech",
    "tw-wudijo",
    "do-7180846",
    "do-1535121",
    "hu-257085",
    "tw-riotgames",
]
history = [
    "bi-77777",
    "tw-lpl",
    "tw-ChrisTitusTech",
    "tw-christitustech",
    "do-156277",
    "tw-endicci",
    "tw-elajjaz",
    "do-787747",
    "tw-Bawkbasoup",
    "tw-PalmBee",
    "tw-the_happy_hob",
    "tw-wudijo",
    "do-610588",
    "tw-csharpfritz",
    "tw-distortion2",
    "hu-572329",
    "do-1535121",
    "tw-missmikkaa",
    "do-718133",
    "do-93589",
    "do-7180846",
    "do-21267",
    "tw-riotgames",
    "hu-257085",
    "bi-545068",
]
