#!/bin/sh

# DO NOT DELETE this file or move it!!
# Startup file for Hyprland used by sddm

# Changing the exports below is not recommended
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# the line below may help with multiple monitors
#export WLR_EGL_NO_MODIFIERS=1

#Add your own exports below this line

export GDK_BACKEND=wayland,x11
export QT_QPA_PLATFORM="wayland;xcb"
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
# export LIBSEAT_BACKEND=logind

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

exec Hyprland
