# hyprlock 锁屏配置(简约版,可自行美化)
# 官方文档: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

background {
    monitor =
    path = screenshot
    blur_size = 400
    blur_passes = 3
    noise = 0.0117
}

input-field {
    monitor =
    size = 300, 40
    outline_thickness = 2
    dots_center = true
    fade_on_empty = false
    placeholder_text = 输入密码...
    position = 0, 120
}

label {
    monitor =
    text = $TIME
    font_size = 60
    position = 0, 200
}
