# hypridle 空闲管理(替代以前没有的自动锁屏/息屏)
# 官方文档: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    ignore_dbus_inhibit = false
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 10 分钟无操作锁屏
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 15 分钟无操作关闭屏幕
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
